### ISSUE TITLE
Mod crashes on Fabric

### ISSUE THREAD

**Issue by enduum** [adoxentor/BundlesPlus#4]
Right-clicking any inventory GUI with bundles plus active on Fabric causes an immediate crash. [Crash log.](https://pastebin.com/9WNLLEFf)

While testing this I also discovered that bundles plus crashes on startup if Mod Menu is not also active, though Mod Menu isn't listed as a dependency on curseforge.

When used on Forge no such issues occur.

Versions are all the most recent as of the past hour, but this crash has been plaguing me for a couple days and there's been a good few updates in that time lol.

**Comment by adoxentor** [comment]
I'll need a full log to find the issue causing the crash, I believe it is a conflict.
The mod menu issue will be fixed next version (no dependency).
If you can also add an export of the cf modpack I'll try it out myself.

**Comment by adoxentor** [comment]
fixed 0.1.5
